services:
  - type: web
    name: ssu-extra-bot
    env: docker
    plan: free
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: SSU_ID
        sync: false
      - key: SSU_PASSWORD
        sync: false
    dockerfilePath: ./Dockerfile
    context: .
    autoDeploy: true
    healthCheckPath: /health